// <auto-generated />
using System;
using CoffeeBeanAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeBeanAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250201232233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeBeanAPI.Models.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasPrecision(18, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<bool>("isBOTD")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("CoffeeBeanAPI.Models.BeanOfTheDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SelectedDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.HasIndex("SelectedDate")
                        .IsUnique();

                    b.ToTable("BeanOfTheDays");
                });

            modelBuilder.Entity("CoffeeBeanAPI.Models.BeanOfTheDay", b =>
                {
                    b.HasOne("CoffeeBeanAPI.Models.Bean", "Bean")
                        .WithMany()
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bean");
                });
#pragma warning restore 612, 618
        }
    }
}
